@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.tmcb_lib.energy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;