modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/TheMCBrothers/TheMCBrosLib/issues"
license = "MIT License"

[[mods]]
    modId = "tmcb_lib"
    version = "${file.jarVersion}"
    displayName = "TheMCBrosLib"
    updateJSONURL = "https://forge.curseupdate.com/387586/tmcb_lib"
    displayURL = "https://themcbrothers.net/"
    logoFile = "logo.png"
    credits = "Some stuff inspired by JEI, Mekanism, Mantle"
    authors = "TheMCBrothers"
    description = '''
    Library Mod for mods by TheMCBrothers.
    '''
[[dependencies.tmcb_lib]] #optional
    modId = "forge"
    mandatory = true
    versionRange = "[44,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tmcb_lib]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3,1.20)"
    ordering = "NONE"
    side = "BOTH"
