@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.lib.registration.deferred;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;