@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.tmcb_lib.crafting.ingredient;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;