@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.tmcb_lib.crafting.ingredient;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;