@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.lib.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;